Models/Entities/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFLogin.Models.Entities
{
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        
    }
}

Models/ErrorViewModel.cs
using System;

namespace EFLogin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Services/Application/ISignInService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFLogin.Models.ViewModels;
using EFLogin.Models.Entities;

namespace EFLogin.Models.Services.Application
{
    public interface ISignInService
    {
        Task<User> CreateNewUser(string Nome, string Email, string Password, string Country);

    }
}

Models/Services/Application/SignInService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EFLogin.Models.Entities;
using EFLogin.Models.ViewModels;
//using EFLogin.Models.Services.Infrastructure;
using Microsoft.EntityFrameworkCore;



namespace EFLogin.Models.Services.Application
{
    public class SignInService : ISignInService
    {
        private readonly UserDbContext dbContext;


        public SignInService(UserDbContext dbContext)
        {
            this.dbContext = dbContext;
        }


        public async Task<User> CreateNewUser(string Nome, string Email, string Password, string Country)
        {

            await dbContext.Users.InsertOnSubmit(user => new User
            {
                user.Name = Nome,
                user.Email = Email,
                user.Password = Password,
                user.Country = Country
            });
            dbContext.SubmitChanges();

            

        }

    }
}

Models/Services/Infrastructure/UserDbContext.cs
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using EFLogin.Models.Entities;

namespace EFLogin.Models.Entities
{
    public partial class UserDbContext : DbContext
    {

        public UserDbContext() { }

        public UserDbContext(DbContextOptions<UserDbContext> options)
                    : base(options)
        {
        }

        public virtual DbSet<User> Users { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
                optionsBuilder.UseSqlite("Data Source=Data/Utenti.db");
            }
        }



        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "2.2.6-servicing-10079");
            //Mappatura con le Fluent API
            modelBuilder.Entity<User>()
            .ToTable("Users");

            modelBuilder.Entity<User>()
            .Property(u => u.Id)
            .HasColumName("ID");

            modelBuilder.Entity<User>()
            .Property(u => u.Password)
            .HasColumName("Password");

            modelBuilder.Entity<User>()
            .Property(u => u.Name)
            .HasColumnName("Name");

            modelBuilder.Entity<User>()
            .Property(u => u.Country)
            .HasColumnName("Country");

            modelBuilder.Entity<User>()
            .Property(u => u.Email)
            .HasColumnName("Email");
        }
        




    }
}

Models/ViewModels/UserDetailViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EFLogin.Models.ViewModels
{
    public class UserDetailModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Country { get; set; }
        public string Password { get; set; }




    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EFLogin.Models;

namespace EFLogin.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        


       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/LoggedController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace EFLogin.Controllers
{
    //[Route("[controller]")]
    public class LoggedController : Controller
    {
        //private readonly ILogger<LoggedController> _logger;

        /*public LoggedController(ILogger<LoggedController> logger)
        {
            _logger = logger;
        }*/

        public IActionResult Index()
        {
            return View();
        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/SignInController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using EFLogin.Models.Services.Application;
using EFLogin.Models.Entities;


namespace EFLogin.Controllers
{
    //[Route("[controller]")]
    public class SignInController : Controller
    {
        //private readonly ILogger<SignInController> _logger;

        /*public SignInController(ILogger<SignInController> logger)
        {
            _logger = logger;
        }*/

        public IActionResult Index()
        {

            
            return View();
        }

        public IActionResult Registrazione(string Nome, string Email, string Password, string Country)
        {
            User user = CreateNewUser(Nome, Email, Password, Country);

            return Content("Registrazione avvenuta yuppie");

        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Home/Index.cshtml
<form action="/SignIn/" method="get" enctype="multipart/form-data">
    <caption>
        <h2></h2>
    </caption>


    <input type="hidden" name="id" value="" />


    <fieldset class="form-group">
        <label>User Name</label> <input type="text" value="" class="form-control" name="nome" required="required">
    </fieldset>

    <fieldset class="form-group">
        <label>User Email</label> <input type="text" value="" class="form-control" name="email">
    </fieldset>

    <button type="submit" class="btn btn-success">Login</button>
</form>

<br/>


<form asp-controller="SignIn" asp-action="Index" method="post">
     
    
    <button type="submit" class="btn btn-success">Registrati</button>
</form>

Views/Logged/Index.cshtml
<nav class="navbar navbar-expand-md navbar-dark" style="background-color: tomato">
    <div>
        <a href="" class="navbar-brand"> User Management App </a>
    </div>

    <ul class="navbar-nav">
        <li><a href="" class="nav-link">Users</a></li>
    </ul>
</nav>
<br>
<div class="row">
    <div class="container">
        <h3 class="text-center">List of Users</h3>
        <hr>
        <div class="container text-left">
            <a href="#" class="btn btn-success">Add New User</a>
        </div>
        <br>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Country</th>
                </tr>
            </thead>
            <tbody>
                /*per ogni utente presente nel database mostrare i suoi dati
                <tr>
                    <td>//ID</td>
                    <td>//Nome</td>
                    <td>//Email</td>
                    <td>//Nazione</td>
                    <td><a href="/*Link aggiornamento utente*/">updateUser</a></td>
                    <td><a href="/*Link cancellare utente*/">deleteUser</a></td>
                </tr>
                */
            </tbody>
        </table>
    </div>
</div>

</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EFLogin</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">EFLogin</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - EFLogin - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/SignIn/Index.cshtml
<p>Registrati</p>
<form action="Registrazione" method="get" enctype="multipart/form-data">

	<caption>
		<h2></h2>
	</caption>


	<input type="hidden" name="id" value="" />


	<fieldset class="form-group">
		<label>User Name</label> <input type="text" value=" " class="form-control" name="Nome" required="required">
	</fieldset>

	<fieldset class="form-group">
		<label>User Email</label> <input type="text" value="" class="form-control" name="Email">
	</fieldset>


	<fieldset class="form-group">
		<label>User Password</label> <input type="text" value="" class="form-control" name="Password">
	</fieldset>

	<fieldset class="form-group">
		<label>User Country</label> <input type="text" value="" class="form-control" name="Country">
	</fieldset>

	<button type="submit" class="btn btn-success"></button>
</form>